kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bare-block-csi-cds-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName:  bare-block-csi-csd-sc
  resources:
    requests:
      storage: 500Gi