apiVersion: v1
kind: Pod
metadata:
  name: oss-csi-cds-pod
spec:
  containers:
  - name: "hello-world"
    image: "tutum/hello-world"
    volumeMounts:
    - name: pvc-oss
      mountPath: "/data"
  volumes:
  - name: pvc-oss
    persistentVolumeClaim:
      claimName: oss-cds-pvc
