apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oss-cds-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: oss-csi-pv
