apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eks-disk-cds-csi-cluster-role-bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eks-disk-cds-csi-cluster-role
subjects:
  - kind: ServiceAccount
    name: eks-disk-cds-csi-sa
    namespace: kube-system