---
apiVersion: v1
kind: Secret
metadata:
  name: eks-secrets
  namespace: kube-system
type: Opaque
data:
  access_key_id: '{access_key_id}'
  access_key_secret: '{access_key_secret}'

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cds-properties
  namespace: kube-system
data:
  k8s_cluster_id: "{k8s_cluster_id}"
  oversea: "{oversea}"
  openapi_host: "{openapi_host}"
  openapi_schema: "{openapi_schema}"
  lb_openapi_host: "{lb_openapi_host}"
  vpc_id: "{vpc_id}"