apiVersion: v1
kind: Service
metadata:
  labels:
    name: eks-disk-csi-provisioner
  name: eks-disk-csi-provisioner
  namespace: kube-system
spec:
  ports:
    - name: healthz
      port: 9810
  selector:
    type: eks-disk-csi-provisioner
