apiVersion: v1
kind: Pod
metadata:
  name: block-csi-cds-pod
spec:
  containers:
  - name: "hello-world"
    image: "tutum/hello-world"
    volumeMounts:
    - name: pvc-block-sc
      mountPath: "/data"
  volumes:
  - name: pvc-block-sc
    persistentVolumeClaim:
      claimName: block-csi-cds-pvc