kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: block-csi-cds-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: block-csi-csd-sc
  resources:
    requests:
      storage: 500Gi