apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: block-csi-csd-sc
parameters:
  fstype: "ext4"
  storageType: "high_disk"
  siteId: "beijing001"
  clusterId: "volumeID-testing001"
  zoneId: "WuxiA-POD10-CLU02"
provisioner: block.csi.cds.net
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer    # Immediate