apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: block-csi-csd-sc
parameters:
  fstype: "ext4"
  StorageType: "high_disk"
  readOnly: "true"
  siteID: "beijing001"
  clusterID: "volumeID-testing001"
provisioner: block.csi.cds.net
reclaimPolicy: Delete
volumeBindingMode: Immediate   # WaitForFirstConsumer