kind: Service
apiVersion: v1
metadata:
  name: block-csi-provisioner
  namespace: kube-system
  labels:
    name: block-csi-provisioner
spec:
  selector:
    type: block-csi-provisioner
  ports:
  - name: healthz
    port: 9808
