apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: disk-csi-csd-sc
parameters:
  fsType: ext4
  region: CN_Suqian
  zone: CN_Suqian_B
  storageType: SSD
provisioner: ebs-disk.csi.cds.net
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: disk-csi-cds-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: disk-csi-csd-sc
  resources:
    requests:
      storage: 24Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: disk-csi-cds-pod
spec:
  containers:
    - name: "nginx-test"
      image: "nginx:latest"
      volumeMounts:
        - name: pvc-disk-sc
          mountPath: "/data"
  volumes:
    - name: pvc-disk-sc
      persistentVolumeClaim:
        claimName: disk-csi-cds-pvc