apiVersion: v1
kind: Pod
metadata:
  name: disk-csi-cds-pod
spec:
  containers:
    - name: "nginx-test"
      image: "nginx:latest"
      volumeMounts:
        - name: pvc-disk-sc
          mountPath: "/data"
  volumes:
    - name: pvc-disk-sc
      persistentVolumeClaim:
        claimName: disk-csi-cds-pvc