kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: disk-csi-cds-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: disk-csi-csd-sc
  resources:
    requests:
      storage: 24Gi