apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: disk-csi-csd-sc
parameters:
  fsType: ext4
  azId: SR_SaoPaulo_A
  storageType: SSD
provisioner: ebs-disk.csi.cds.net
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer