---
apiVersion: v1
kind: Secret
metadata:
  name: cck-secrets
  namespace: kube-system
type: Opaque
data:
  access_key_id: '28e44dda6a1211eda59242de7ed185aa'
  access_key_secret: 'afee6ab5a320b354d07b24287cf73c18'

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cds-properties
  namespace: kube-system
data:
  k8s_cluster_id: "dyl-test"
  site_id: "CN_BeijingA"
  site_name: "北京"
  oversea: "false"