apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: test-sc-delete
parameters:
  fsType: ext4
  storageType: SSD
  zone: CN_Suqian_B # 可用区Code
  region: CN_Suqian # 区域Code
  subjectId: "00000"  # 测试金项目id，客户在试用时填写，具体的id值请联系管理员
provisioner: eks-disk.csi.cds.net
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
  - matchLabelExpressions:
      - key: topology.kubernetes.io/zone
        values:
          - CN_Suqian_B  # 可用区Code
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc-rwmany-sc-retain
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: test-sc-retain
  resources:
    requests:
      storage: 80Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-pod-pvc-rwmany-sc-retain-single-volume
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - nginx
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: "nginx-test"
          image: "nginx:latest"
          volumeMounts:
            - name: volume1
              mountPath: "/test_path1"
      volumes:
        - name: volume1
          persistentVolumeClaim:
            claimName: test-pvc-rwmany-sc-retain