apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: disk-csi-cds-controller
  namespace: kube-system
spec:
  replicas: 1
  serviceName: disk-csi-provisioner
  selector:
    matchLabels:
      app: disk-csi-cds-controller
  template:
    metadata:
      labels:
        app: disk-csi-cds-controller
        type: csi-provisioner
    spec:
      nodeSelector:
        node.cck.net/role.infra: "True"
      serviceAccount: disk-cds-csi-sa
      hostNetwork: true
      hostPID: true
      priorityClassName: system-cluster-critical
      tolerations:
      - key:
        operator: Exists
      containers:
      - name: csi-controller-server
        image: registry-bj.capitalonline.net/cck/cds-csi-driver:latest
        imagePullPolicy: "Always"
        args:
        - "--endpoint=$(CSI_ENDPOINT)"
        - "--v=5"
        - "--driver=disk.csi.cds.net"
        env:
        - name: CSI_ENDPOINT
          value: unix://socketDir/csi.sock
        - name: ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: access_key_id
              name: cck-secrets
        - name: ACCESS_KEY_SECRET
          valueFrom:
            secretKeyRef:
              key: access_key_secret
              name: cck-secrets
        - name: CDS_OVERSEA
          valueFrom:
            configMapKeyRef:
              name: cds-properties
              key: oversea
        securityContext:
          privileged: true
        volumeMounts:
        - name: host-log
          mountPath: /var/log/
        - name: socket-dir
          mountPath: /socketDir/
        - name: etc
          mountPath: /host/etc
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - ps -ef | grep cds-csi-driver | grep disk.csi.cds.net | grep -v grep
          failureThreshold: 8
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
      - name: csi-provisioner
        image: registry-bj.capitalonline.net/cck/csi-provisioner:v1.5.0
        args:
        - "--csi-address=$(ADDRESS)"
        - "--v=5"
        env:
        - name: ADDRESS
          value: /socketDir/csi.sock
        volumeMounts:
        - name: socket-dir
          mountPath: /socketDir
      - name: liveness-probe
        image: registry-bj.capitalonline.net/cck/csi-livenessprobe:v2.0.0
        args:
        - "--csi-address=/csi/csi.sock"
        - "--health-port=9811"
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
      - name: csi-attacher
        image: registry-bj.capitalonline.net/cck/csi-attacher:v1.2.0
        args:
        - --csi-address=$(ADDRESS)
        - --v=5
        - --leader-election=true
        - --leader-election-type=leases
        env:
        - name: ADDRESS
          value: /var/lib/csi/sockets/pluginproxy/csi.sock
        volumeMounts:
        - name: socket-dir
          mountPath: /var/lib/csi/sockets/pluginproxy/
      volumes:
      - name: socket-dir
        emptyDir: {}
      - name: host-log
        hostPath:
          path: /var/log/
      - name: etc
        hostPath:
          path: /etc
  updateStrategy:
    type: RollingUpdate
