apiVersion: v1
kind: Pod
metadata:
  name: nas-csi-cds-pod-subpath
spec:
  containers:
    - name: "hello-world"
      image: "tutum/hello-world"
      volumeMounts:
        - name: pvc-nas-sc
          mountPath: "/data"
  volumes:
    - name: pvc-nas-sc
      persistentVolumeClaim:
        claimName: nas-csi-cds-pvc-sc-subpath