apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nas-csi-csd-sc-subpath
parameters:
  volumeAs: subpath
  server: "140.210.75.195"
  path: "/nfsshare"
  vers: "4.0"
  threshold: "90"
  options: noresvport
  archiveOnDelete: "true"
provisioner: nas.csi.cds.net
reclaimPolicy: Delete