apiVersion: v1
kind: Pod
metadata:
  name: nas-csi-cds-pod
spec:
  containers:
    - name: "hello-world"
      image: "tutum/hello-world"
      volumeMounts:
        - name: pvc-nas
          mountPath: "/data"
  volumes:
    - name: pvc-nas
      persistentVolumeClaim:
        claimName: nas-csi-cds-pvc