apiVersion: v1
kind: ServiceAccount
metadata:
  name: nas-cds-csi-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nas-cds-csi-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
  - update
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - storage.k8s.io
  resources:
  - csinodes
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - watch
  - list
  - delete
  - update
  - create
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - watch
  - list
  - delete
  - update
  - create
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - csi.storage.k8s.io
  resources:
  - csinodeinfos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - volumeattachments
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshotclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshotcontents
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - delete
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshots
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - list
  - watch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nas-cds-csi-cluster-role-bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nas-cds-csi-cluster-role
subjects:
- kind: ServiceAccount
  name: nas-cds-csi-sa
  namespace: kube-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: nas-csi-provisioner
  name: nas-csi-provisioner
  namespace: kube-system
spec:
  ports:
  - name: healthz
    port: 9809
  selector:
    type: nas-csi-provisioner
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nas-csi-cds-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nas-csi-cds-controller
  serviceName: nas-csi-provisioner
  template:
    metadata:
      labels:
        app: nas-csi-cds-controller
        type: csi-provisioner
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      containers:
      - args:
        - --endpoint=$(CSI_ENDPOINT)
        - --v=5
        - --driver=nas.csi.cds.net
        env:
        - name: CSI_ENDPOINT
          value: unix://socketDir/csi.sock
        - name: ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: access_key_id
              name: cck-secrets
        - name: ACCESS_KEY_SECRET
          valueFrom:
            secretKeyRef:
              key: access_key_secret
              name: cck-secrets
        - name: CDS_OVERSEA
          valueFrom:
            configMapKeyRef:
              key: oversea
              name: cds-properties
        - name: CDS_CLUSTER_ID
          valueFrom:
            configMapKeyRef:
              key: k8s_cluster_id
              name: cds-properties
        image: capitalonline/cds-csi-driver:v2.0.3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - ps -ef | grep cds-csi-driver | grep nas.csi.cds.net | grep -v grep
          failureThreshold: 8
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
        name: csi-controller-server
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/log/
          name: host-log
        - mountPath: /socketDir/
          name: socket-dir
        - mountPath: /host/etc
          name: etc
      - args:
        - --csi-address=$(ADDRESS)
        - --v=5
        env:
        - name: ADDRESS
          value: /socketDir/csi.sock
        image: capitalonline/csi-provisioner:v3.5.0
        name: csi-provisioner
        volumeMounts:
        - mountPath: /socketDir
          name: socket-dir
      - args:
        - --csi-address=/csi/csi.sock
        - --health-port=9809
        image: capitalonline/csi-livenessprobe:v2.11.0
        name: liveness-probe
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
      priorityClassName: system-cluster-critical
      serviceAccount: nas-cds-csi-sa
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      - effect: NoSchedule
        key: node-role.cck.net/infra
      volumes:
      - emptyDir: {}
        name: socket-dir
      - hostPath:
          path: /var/log/
        name: host-log
      - hostPath:
          path: /etc
        name: etc
  updateStrategy:
    type: RollingUpdate
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nas-csi-cds-node
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: nas-csi-cds-node
  template:
    metadata:
      labels:
        app: nas-csi-cds-node
    spec:
      containers:
      - args:
        - --endpoint=$(CSI_ENDPOINT)
        - --v=5
        - --driver=nas.csi.cds.net
        env:
        - name: CSI_ENDPOINT
          value: unix://var/lib/kubelet/plugins/nas.csi.cds.net/csi.sock
        image: capitalonline/cds-csi-driver:v2.0.3
        imagePullPolicy: IfNotPresent
        name: nas-csi-node-server
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - SYS_ADMIN
          privileged: true
        volumeMounts:
        - mountPath: /var/lib/kubelet/
          mountPropagation: Bidirectional
          name: kubelet-dir
        - mountPath: /var/log/
          name: host-log
        - mountPath: /host/etc
          name: etc
      - args:
        - --v=5
        - --csi-address=$(ADDRESS)
        - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
        env:
        - name: ADDRESS
          value: /var/lib/kubelet/plugins/nas.csi.cds.net/csi.sock
        - name: DRIVER_REG_SOCK_PATH
          value: /var/lib/kubelet/plugins/nas.csi.cds.net/csi.sock
        image: capitalonline/csi-node-driver-registrar:v2.9.0
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - rm -rf /registration/nas.csi.cds.net /registration/nas.csi.cds.net-reg.sock
        name: nas-driver-registrar
        volumeMounts:
        - mountPath: /var/lib/kubelet/
          name: kubelet-dir
        - mountPath: /registration/
          name: registration-dir
      - args:
        - --csi-address=/var/lib/kubelet/plugins/nas.csi.cds.net/csi.sock
        - --health-port=9810
        image: capitalonline/csi-livenessprobe:v2.11.0
        name: nas-liveness-probe
        volumeMounts:
        - mountPath: /var/lib/kubelet/
          name: kubelet-dir
      hostNetwork: true
      hostPID: true
      priorityClassName: system-node-critical
      serviceAccount: nas-cds-csi-sa
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      - effect: NoSchedule
        key: node-role.cck.net/infra
      volumes:
      - hostPath:
          path: /var/lib/kubelet
          type: Directory
        name: kubelet-dir
      - hostPath:
          path: /var/lib/kubelet/plugins_registry
          type: DirectoryOrCreate
        name: registration-dir
      - hostPath:
          path: /var/log/
        name: host-log
      - hostPath:
          path: /etc
        name: etc
  updateStrategy:
    type: RollingUpdate
---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: nas.csi.cds.net
spec:
  attachRequired: false