---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: ccs-disk.csi.cds.net
spec:
  attachRequired: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ccs-disk-cds-csi-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ccs-disk-cds-csi-cluster-role
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
    verbs:
      - patch
      - get
      - list
      - watch
      - update
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
      - patch
  - apiGroups:
      - storage.k8s.io
    resources:
      - volumeattachments/status
    verbs:
      - patch
  - apiGroups:
      - storage.k8s.io
    resources:
      - csinodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
      - watch
      - list
      - delete
      - update
      - create
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - watch
      - list
      - delete
      - update
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - csi.storage.k8s.io
    resources:
      - csinodeinfos
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - storage.k8s.io
    resources:
      - volumeattachments
    verbs:
      - get
      - patch
      - list
      - watch
      - update
  - apiGroups:
      - snapshot.storage.k8s.io
    resources:
      - volumesnapshotclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - snapshot.storage.k8s.io
    resources:
      - volumesnapshotcontents
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - delete
  - apiGroups:
      - snapshot.storage.k8s.io
    resources:
      - volumesnapshots
    verbs:
      - get
      - list
      - watch
      - update
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - create
      - list
      - watch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - watch
      - list
      - delete
      - update
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ccs-disk-cds-csi-cluster-role-bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ccs-disk-cds-csi-cluster-role
subjects:
  - kind: ServiceAccount
    name: ccs-disk-cds-csi-sa
    namespace: kube-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: ccs-disk-csi-provisioner
  name: ccs-disk-csi-provisioner
  namespace: kube-system
spec:
  ports:
    - name: healthz
      port: 9810
  selector:
    type: ccs-disk-csi-provisioner
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ccs-disk-csi-cds-controller
  namespace: kube-system
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ccs-disk-csi-cds-controller
  serviceName: ccs-disk-csi-provisioner
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ccs-disk-csi-cds-controller
        type: csi-provisioner
    spec:
      containers:
      - args:
        - --endpoint=$(CSI_ENDPOINT)
        - --v=5
        - --driver=ccs-disk.csi.cds.net
        env:
        - name: CSI_ENDPOINT
          value: unix://socketDir/csi.sock
        - name: ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: access_key_id
              name: ccs-secrets
        - name: ACCESS_KEY_SECRET
          valueFrom:
            secretKeyRef:
              key: access_key_secret
              name: ccs-secrets
        - name: API_HOST
          valueFrom:
            configMapKeyRef:
              key: api_host
              name: cds-properties
        - name: CDS_OVERSEA
          valueFrom:
            configMapKeyRef:
              key: oversea
              name: cds-properties
        image: capitalonline/cds-csi-driver:v2.1.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - ps -ef | grep cds-csi-driver | grep ccs-disk.csi.cds.net | grep -v grep
          failureThreshold: 8
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
        name: csi-controller-server
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/log/
          name: host-log
        - mountPath: /socketDir/
          name: socket-dir
        - mountPath: /host/etc
          name: etc
      - args:
        - --csi-address=$(ADDRESS)
        - --v=5
        env:
        - name: ADDRESS
          value: /socketDir/csi.sock
        image: capitalonline/csi-provisioner:v1.5.0
        imagePullPolicy: IfNotPresent
        name: csi-provisioner
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /socketDir
          name: socket-dir
      - args:
        - --csi-address=/csi/csi.sock
        - --health-port=9811
        image: capitalonline/csi-livenessprobe:v2.0.0
        imagePullPolicy: IfNotPresent
        name: liveness-probe
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
      - args:
        - --csi-address=$(ADDRESS)
        - --v=5
        - --leader-election=true
        - --leader-election-type=leases
        env:
        - name: ADDRESS
          value: /var/lib/csi/sockets/pluginproxy/csi.sock
        image: capitalonline/csi-attacher:v1.2.0
        imagePullPolicy: IfNotPresent
        name: csi-attacher
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/csi/sockets/pluginproxy/
          name: socket-dir
      dnsPolicy: ClusterFirst
      hostNetwork: true
      hostPID: true
      nodeSelector:
        node-role.kubernetes.io/master: ""
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: ccs-disk-cds-csi-sa
      serviceAccountName: ccs-disk-cds-csi-sa
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: node-role.cck.net/infra
      volumes:
      - emptyDir: {}
        name: socket-dir
      - hostPath:
          path: /var/log/
          type: ""
        name: host-log
      - hostPath:
          path: /etc
          type: ""
        name: etc
  updateStrategy:
    type: RollingUpdate

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ccs-disk-csi-cds-node
  namespace: kube-system
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ccs-disk-csi-cds-node
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ccs-disk-csi-cds-node
    spec:
      containers:
      - args:
        - --endpoint=$(CSI_ENDPOINT)
        - --v=5
        - --driver=ccs-disk.csi.cds.net
        env:
        - name: CSI_ENDPOINT
          value: unix://var/lib/kubelet/plugins/ccs-disk.csi.cds.net/csi.sock
        - name: ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: access_key_id
              name: ccs-secrets
        - name: ACCESS_KEY_SECRET
          valueFrom:
            secretKeyRef:
              key: access_key_secret
              name: ccs-secrets
        - name: API_HOST
          valueFrom:
            configMapKeyRef:
              key: api_host
              name: cds-properties
        - name: CDS_OVERSEA
          valueFrom:
            configMapKeyRef:
              key: oversea
              name: cds-properties
        image: capitalonline/cds-csi-driver:v2.1.0
        imagePullPolicy: IfNotPresent
        name: ccs-disk-csi-node-server
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - SYS_ADMIN
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/kubelet/
          mountPropagation: Bidirectional
          name: kubelet-dir
        - mountPath: /var/log/
          name: host-log
        - mountPath: /host/etc
          name: etc
        - mountPath: /dev
          name: host-dev
      - args:
        - --v=5
        - --csi-address=$(ADDRESS)
        - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
        env:
        - name: ADDRESS
          value: /var/lib/kubelet/plugins/ccs-disk.csi.cds.net/csi.sock
        - name: DRIVER_REG_SOCK_PATH
          value: /var/lib/kubelet/plugins/ccs-disk.csi.cds.net/csi.sock
        image: capitalonline/csi-node-driver-registrar:v1.2.0
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - rm -rf /registration/ccs-disk.csi.cds.net /registration/ccs-disk.csi.cds.net-reg.sock
        name: disk-driver-registrar
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/kubelet/
          name: kubelet-dir
        - mountPath: /registration/
          name: registration-dir
      - args:
        - --csi-address=/var/lib/kubelet/plugins/ccs-disk.csi.cds.net/csi.sock
        - --health-port=9812
        image: capitalonline/csi-livenessprobe:v2.0.0
        imagePullPolicy: IfNotPresent
        name: disk-liveness-probe
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/kubelet/
          name: kubelet-dir
      dnsPolicy: ClusterFirst
      hostNetwork: true
      hostPID: true
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: ccs-disk-cds-csi-sa
      serviceAccountName: ccs-disk-cds-csi-sa
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: node-role.cck.net/infra
      volumes:
      - hostPath:
          path: /var/lib/kubelet
          type: Directory
        name: kubelet-dir
      - hostPath:
          path: /var/lib/kubelet/plugins_registry
          type: DirectoryOrCreate
        name: registration-dir
      - hostPath:
          path: /var/log/
          type: ""
        name: host-log
      - hostPath:
          path: /etc
          type: ""
        name: etc
      - hostPath:
          path: /dev
          type: ""
        name: host-dev
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate

