apiVersion: v1
kind: Pod
metadata:
  name: pod-filesystem
spec:
  containers:
  - name: "hello-world"
    image: "tutum/hello-world"
    volumeMounts:
    - name: pvc-nas-sc
      mountPath: "/data"
  volumes:
  - name: pvc-nas-sc
    persistentVolumeClaim:
      claimName: pvc-sc-filesystem